---
- hosts: localhost
  vars:
    - user: bmon
    - server_ip: 192.241.198.236
    - bmon_domain: test.bmon.org
    - bmon_site_title: BMON Test Site
    - admin_email_name: Alan Mitchell
    - admin_email_address: tabb99@gmail.com
    - allowed_hosts:
      - "{{ bmon_domain }}"
      - www.{{ bmon_domain }}
      - "{{ server_ip }}"
      - localhost
    - email_smtp_host:  smtp.gmail.com
    - email_username: something@gmail.com
    - email_password: PasswordForAbove
    - superuser_name: admin
    - superuser_password: password
    - superuser_email: super@gmail.com
    - lets_encrypt_email: {{ admin_email_address }}

  tasks:
    - name: Install system packages
      become: yes
      apt: 
        name:
          - git 
          - pipenv
          - python3-pip 
          - python3-dev 
          - nginx 
          - ufw
          - curl 
          - sqlite3
          - pwgen
          - tree
          - unzip
          - certbot 
          - python3-certbot-nginx
        state: latest

    - name: Upgrade pip
      become: yes
      pip:
        name: pip
        extra_args: --upgrade

    - name: Install visidata data viewing tool
      pip:
        name: visidata

    - name: Clone BMON Repository
      git:
        repo: https://github.com/alanmitchell/bmon.git
        dest: /home/{{ user }}/bmon
        force: no
        version: bare-server

    - name: Install BMON Dependencies
      shell:
        cmd: pipenv sync
        chdir: /home/{{ user }}/bmon/

    - name: Make a BMON Storage Key
      shell:
        cmd: pwgen 12 1
      register: store_key

    - name: Make a Django Secret Key
      shell:
        cmd: pwgen 20 1
      register: django_secret_key

    - name: Make a BMON settings.py file from a template
      ansible.builtin.template:
        src: "/home/{{ user }}/bmon/bmon/settings_example.py"
        dest: "/home/{{ user }}/bmon/bmon/settings.py"

    - name: Run a number of manage.py commands on the Django app
      shell:
        cmd: pipenv run python manage.py {{ item }}
        chdir: /home/{{ user }}/bmon/
      loop:
        - makemigrations
        - migrate
        - collectstatic --noinput
        - loaddata init_data.yaml

    - name: Create the super user
      shell:
        cmd: echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('{{ superuser_name }}', '{{ superuser_email }}', '{{ superuser_password }}')" | pipenv run python manage.py shell
        chdir: /home/{{ user }}/bmon/

    - name: Find the virtual env directory
      shell:
        cmd: pipenv --venv
        chdir: /home/{{ user }}/bmon
      register: venv_dir

    - name: Make systemd service files
      become: yes
      ansible.builtin.template:
        src: /home/{{ user }}/bmon-install/bmon.service.j2
        dest: /etc/systemd/system/bmon.service

    - name: Make socket file
      become: yes
      copy:
        src: /home/{{ user }}/bmon-install/bmon.socket
        dest: /etc/systemd/system/bmon.socket

    - name: Start and Enable the socket
      become: yes
      ansible.builtin.systemd:
        name: bmon.socket
        state: started
        enabled: yes

    - name: Make Nginx site file for raw IP address
      become: yes
      ansible.builtin.template:
        src: /home/{{ user }}/bmon-install/nginx-bmon-ip.j2
        dest: /etc/nginx/sites-available/bmon-ip

    - name: Create a symbolic link to enable site for IP address
      become: yes
      ansible.builtin.file:
        src: /etc/nginx/sites-available/bmon-ip
        dest: /etc/nginx/sites-enabled/bmon-ip
        state: link

    - name: Make Nginx site file for domain
      become: yes
      ansible.builtin.template:
        src: /home/{{ user }}/bmon-install/nginx-bmon.j2
        dest: /etc/nginx/sites-available/bmon

    - name: Create a symbolic link to enable site for domain
      become: yes
      ansible.builtin.file:
        src: /etc/nginx/sites-available/bmon
        dest: /etc/nginx/sites-enabled/bmon
        state: link

    - name: Restart Nginx
      become: yes
      ansible.builtin.systemd:
        name: nginx
        state: restarted

    - name: Make sure SSH is enabled on UFW firewall
      become: yes
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow Nginx ports in firewall
      become: yes
      ufw:
        state: enabled
        rule: allow
        name: Nginx Full

    - name: Install Let's Encrypt Certificate
      become: yes
      shell:
        cmd: certbot --nginx --noninteractive --agree-tos -m {{ lets_encrypt_email }} --redirect -d {{ bmon_domain }} -d www.{{ bmon_domain }}
