---
- hosts: localhost
  vars:
    - user: bmon
    - ssh_key: .ssh/id_rsa
    - bmon_site_title: BMON Test Site
    - admin_email_name: Alan Mitchell
    - admin_email_address: tabb99@gmail.com
    - allowed_hosts:
      - sewardwatch.org
      - 198.199.116.9
      - localhost
    - email_smtp_host:  smtp.gmail.com
    - email_username: something@gmail.com
    - email_password: PasswordForAbove

  tasks:
  
    - name: Run a number of manage.py commands on the Django app
      shell:
        cmd: pipenv run python manage.py {{ item }}
        chdir: /home/{{ user }}/bmon/
      loop:
        - makemigrations
        - migrate
        - collectstatic --noinput
        - loaddata init_data.yaml
