---
- hosts: localhost
  vars:
    - user: bmon

  tasks:
    - name: Find the virtual env directory
      shell:
        cmd: pipenv --venv
        chdir: /home/{{ user }}/bmon
      register: venv_dir

    - name: Make systemd service files
      become: yes
      ansible.builtin.template:
        src: /home/{{ user }}/bmon-install/bmon.service.j2
        dest: /etc/systemd/system/bmon.service

    - name: Make socket file
      become: yes
      copy:
        src: /home/{{ user }}/bmon-install/bmon.socket
        dest: /etc/systemd/system/bmon.socket
