---
- hosts: localhost
  vars:
    - user: bmon
    - server_ip: 192.241.198.236
    - bmon_domain: test.bmon.org

  tasks:
    - name: Find the virtual env directory
      shell:
        cmd: pipenv --venv
        chdir: /home/{{ user }}/bmon
      register: venv_dir

    - name: Make systemd service files
      become: yes
      ansible.builtin.template:
        src: /home/{{ user }}/bmon-install/bmon.service.j2
        dest: /etc/systemd/system/bmon.service

    - name: Make socket file
      become: yes
      copy:
        src: /home/{{ user }}/bmon-install/bmon.socket
        dest: /etc/systemd/system/bmon.socket

    - name: Start and Enable the socket
      become: yes
      ansible.builtin.systemd:
        name: bmon.socket
        state: started
        enabled: yes

    - name: Make Nginx site file for raw IP address
      become: yes
      ansible.builtin.template:
        src: /home/{{ user }}/bmon-install/nginx-bmon-ip.j2
        dest: /etc/nginx/sites-available/bmon-ip

    - name: Create a symbolic link to enable site for IP address
      become: yes
      ansible.builtin.file:
        src: /etc/nginx/sites-available/bmon-ip
        dest: /etc/nginx/sites-enabled/bmon-ip
        state: link

    - name: Make Nginx site file for domain
      become: yes
      ansible.builtin.template:
        src: /home/{{ user }}/bmon-install/nginx-bmon.j2
        dest: /etc/nginx/sites-available/bmon

    - name: Create a symbolic link to enable site for domain
      become: yes
      ansible.builtin.file:
        src: /etc/nginx/sites-available/bmon
        dest: /etc/nginx/sites-enabled/bmon
        state: link

    - name: Restart Nginx
      become: yes
      ansible.builtin.systemd:
        name: nginx
        state: restarted

    - name: Make sure SSH is enabled on UFW firewall
      become: yes
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow Nginx ports in firewall
      become: yes
      ufw:
        state: enabled
        rule: allow
        name: Nginx Full
