---
- hosts: localhost
  vars_files:
    - variables.yaml

  tasks:
  - name: Make sure the Django database backup cron job is present.
    ansible.builtin.cron:
      name: BMON Django Datbase Backup Cron job
      minute: "18"
      hour: "11,23"
      job: "aws s3 sync {{ install_dir }}/bak s3://bmon-backup.analysisnorth.com/{{ bmon_domain }}/django"
      disabled: yes

  - name: Make sure the Sensor Reading database backup cron job is present.
    ansible.builtin.cron:
      name: BMON Sensor Reading Datbase Backup Cron job
      minute: "25"
      hour: "11,23"
      job: "aws s3 sync {{ install_dir }}/bmsapp/readingdb/data/bak  s3://bmon-backup.analysisnorth.com/{{ bmon_domain }}/data --storage-class ONEZONE_IA"
      disabled: yes
