---
- hosts: localhost
  vars:
    - install_dir: "{{ lookup('env', 'HOME') }}/test/"
    - bmon_domain: test.bmon.org

  tasks:
    - name: Clone BMON Repository
      git:
        repo: https://github.com/alanmitchell/bmon.git
        dest: "{{ install_dir }}"
        force: no
        version: bare-server
