---
- hosts: localhost
  vars:
    - install_dir: "{{ lookup('env', 'HOME') }}/bmon"
    - bmon_domain: test.bmon.org

  tasks:
  - name: Certbot test
    become: yes
    shell:
      cmd: certbot --nginx --noninteractive --agree-tos -m tabb99@gmail.com --redirect -d {{ bmon_domain }} -d www.{{ bmon_domain }}
